### ISSUE TITLE
Error: Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by younesherlock** [reduxjs/react-redux#1007]
Hello,

This issue (`Error: Actions must be plain objects. Use custom middleware for async actions.`) is apparently famous when we do some research on internet, and in my case, it's not obvious at all. I have found here and on SOF many root causes that may throw this, and I checked my code to make sure I'm doing the right thing, but couldn't spot what I'm missing.

I have tried:
1- ` onInitUsers: bindActionCreators(actionCreators.initUsers, dispatch),`
2- `actions: bindActionCreators(actionCreators, dispatch),`
3- `onInitUsers: actionCreators.initUsers`

...but vainly :( 

I want to understand why this is happening, and also, if we can get this error/root cause more expressive.

Actually, when I comment the `onInitUsers();` call in the `componentDidMount()` function, I no more have the error, but my action isn't triggered.

My `UserHandler` component is as follow:

	import React, { Component } from 'react';
	import { connect } from 'react-redux';
	import PropTypes from 'prop-types';

	import * as actionCreators from '../../store/actions/actions';

	class UserHandler extends Component {
	  componentDidMount() {
		const { onInitUsers } = this.props;
		onInitUsers();
	  }

	  render() {
		// some code
		return (          
			{/* SOME JSX */}
		);
	  }
	}

	const mapStateToProps = state => ({
	  //    state to props mapping
	});

	const mapDispatchToProps = dispatch => ({
	  onUserEdition: username => dispatch(actionCreators.editUser(username)),
	  onUserSelection: username => dispatch(actionCreators.fetchSelectedUser(username)),
	  onInitUsers: () => dispatch(actionCreators.initUsers()),
	});

	// PropTypes definition and defaultProps

	export default connect(mapStateToProps, mapDispatchToProps)(UserHandler);
	And in my actionCreators file, here's what I defined:

	const initUsersStart = createAction(INIT_USERS_START);
	const setUsers = createAction(SET_USERS, users => ({ users }));
	const initUsersError = createAction(INIT_USERS_ERROR, error => ({ error }));

	const initUsers = () => (dispatch) => {
	  dispatch(initUsersStart());
	  return axios.get('/users')
		.then(
		  response => dispatch(setUsers(response.data)),
		)
		.catch(
		  error => dispatch(initUsersError(error)),
		);
	};

I have defined my `actionCreator` like this:

	
	const initUsersStart = createAction(INIT_USERS_START);
	const setUsers = createAction(SET_USERS, users => ({ users }));
	const initUsersError = createAction(INIT_USERS_ERROR, error => ({ error }));

	const initUsers = () => (dispatch) => {
	  dispatch(initUsersStart());
	  return axios.get('/users')
		.then(
		  response => dispatch(setUsers(response.data)),
		)
		.catch(
		  error => dispatch(initUsersError(error)),
		);
	};

Finally, here's how my `store` looks like:

	
	import React from 'react';
	import ReactDOM from 'react-dom';
	import { BrowserRouter } from 'react-router-dom';
	import { createStore, applyMiddleware } from 'redux';
	import { Provider } from 'react-redux';
	import thunk from 'redux-thunk';

	import App from './App';
	import registerServiceWorker from './registerServiceWorker';
	import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
	import reducer from './store/reducers/reducers';

	const store = createStore(
	  reducer, /* preloadedState, */
	  applyMiddleware(thunk),
	  /* eslint-disable no-undef */ /* eslint-disable no-underscore-dangle */
	  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
	  /* eslint-enable */
	);

	// const store = createStore(reducer);

	ReactDOM.render(
	  <Provider store={store}>
		<BrowserRouter>
		  <App />
		</BrowserRouter>
	  </Provider>,
	  /* eslint-disable no-undef */
	  document.getElementById('root'),
	  /* eslint-enable */
	);
	registerServiceWorker();

**Comment by markerikson** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out - you'll probably get a better answer faster. Thanks!

Having said that, I will give you a couple quick suggestions.

First, the root issue is that something that is not a plain action object is reaching the actual store.  You could put a breakpoint in the `dispatch` function in the Redux source code to see what the actual value is (or edit the copy of Redux in your project's `node_modules` folder to add some logging).

Actually, I think I see the problem.  The real issue is that you're passing two separate store enhancers to `createStore`.  One is the middleware enhancer from `applyMiddleware`, the other is the Redux DevTools extension.  You need to "compose" them both together into a combined enhancer.  See the [Configuring Your Store](https://redux.js.org/recipes/configuringyourstore) page in the Redux docs for a copy-pasteable example of how to do this properly.

Two other suggestions:

Instead of writing a `mapDispatch` function by hand, you can use the "object shorthand", and just pass an object full of action creators directly to `connect`.  You already have an object full of action creators from the `import * as actionCreators` statement, so you can just do: `export default connect(mapState, actionCreators)(UserHandler)`.  (That said, the function names are not the same as the prop names you want, so you might need to make a new object instead like `{onUserSelection : actionCreators.fetchSelectedUser}` and pass that instead.)

Also, we've got a [`redux-starter-kit` package](https://github.com/markerikson/redux-starter-kit) we're working on that has a single function to set up your store for you, and automatically adds both `redux-thunk` and the DevTools Extension.  You might want to try using that instead of setting up the store yourself.

Hope that helps!
