### ISSUE TITLE
[BUG] Connect throws error when there is property called store

### ISSUE THREAD

**Issue by LKay** [reduxjs/react-redux#1044]
The problem is in these lines: 

https://github.com/reduxjs/react-redux/blob/dde1a0a11dbb093f718757409b357cd04c9790e3/src/components/connectAdvanced.js#L16

https://github.com/reduxjs/react-redux/blob/dde1a0a11dbb093f718757409b357cd04c9790e3/src/components/connectAdvanced.js#L125

When the wrapped component has a property named `store` passed down from other HoC or just as component property `store.getState()` call throws an error as it tries to execute non existing function on `store` property.

**Comment by markerikson** [comment]
The `connect` API specifically accepts a Redux store as a prop named `store`.  This prop name is effectively reserved for the connected wrapper component.  Please do not pass non-Redux-store value as a prop named `store` to connected components.

**Comment by LKay** [comment]
There should be at least a mention in the documentation about this restriction. Right now if I have another `store` prop created by other HoC in the chain I have to explicitly remap its name inside `mapStateToProps` before wrapping component with `connect()`. That's pretty annoying...

**Comment by markerikson** [comment]
This behavior has been in React-Redux since the beginning, so it's certainly not anything new.  It _is_ mentioned in the existing [API doc page](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#provider), although it's not totally obvious.  We are currently in the previous of completely rewriting the docs - feel free to submit a PR to help with that.

Out of curiosity, what is your use case for passing something else as a prop named `store` to a connected component?  What kind of value is it, and where is it coming from?

Also, note that "remapping" is unlikely to change the behavior, because `connect` explicitly merges together `{ ...ownProps, ...stateProps, ...dispatchProps }`.  All you'd be doing is having it show up at both `ownProps.store` _and_ `stateProps.someOtherField`, so the same value would be appearing as two separate props in the wrapped component.

**Comment by LKay** [comment]
My case is pretty much this:
- I have a eCommerce-like app and one of the entities are stores (thus single item named store).
- There is a custom HoC which acts like a data fetcher for record. The record is fetched from the rest API before the actual component is rendered and result is mapped to injected prop named after the resource name plural/singular.
