### ISSUE TITLE
react-redux 6 components using ReactReduxContext are always updated

### ISSUE THREAD

**Issue by adaniliuk** [reduxjs/react-redux#1136]
**Do you want to request a _feature_ or report a _bug_?** _bug_

**What is the current behavior?**

Components using only `ReactReduxContext` context are always updated (re-rendered) when react-redux v6 is used, while they are not with react-redux v5.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to a CodeSandbox (https://codesandbox.io/s/new) or RN Snack (https://snack.expo.io/) example below:**

There is link to CodeSandbox https://codesandbox.io/s/jzrmxk9xq9 
* `ConnectedComponent` is updated every time store state is changed as expected
* But `NotConnected`component is updated as well 

**What is the expected behavior?**

Behavior is different in react-redux v5 https://codesandbox.io/s/5xxw668w3k
* `ConnectedComponent` is updated every time store state is changed as expected
* But `NotConnected`component is not updated

**Which versions of React, ReactDOM/React Native, Redux, and React-Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React-Redux?**

* react-redux 6.0.0 vs 5.1.1
* react/react-dom 16.6.3
* redux 4.0.1

**Comment by markerikson** [comment]
Saw this over in Reactiflux first.  I'll recap my thoughts here.

Yes, this is a semi-expected side effect of moving to having `<Provider>` subscribe to the state.  `<Provider>` will call `this.setState()` whenever the Redux store state has been updated, which queues a re-render.  A `<Provider>` is normally the outermost component in a tree.  React's default behavior is that when a component re-renders, all of its children re-render recursively, unless stopped by a `shouldComponentUpdate / PureComponent / React.memo` that blocks that subtree from updating.

Given a tree that looks like this:
```
<Provider>
    <UnconnectedApp>
        <ConnectedComponent>
            <UnconnectedChild>
                <ConnectedGrandchild>`
```

I would expect that:

- `<Provider>` will re-render, because it calls `this.setState()`
- `<UnconnectedApp>` will re-render, because it is directly below `<Provider>`
- The `connect` wrapper from `<ConnectedComponent` will have its context consumer re-render, but the wrapped component will only re-render if its props have changed.  Same for `<ConnectedGrandchild>`
- `<UnconnectedChild>` will only re-render if the wrapped component from `<ConnectedComponent>` was updated.

In most apps, I don't think this is going to make a meaningful difference.  Most apps are going to have one or more connected components close to the root of the tree, thus blocking the `<Provider>` renders from rippling all the way down.

If this is a concern, one option would be to wrap your root component in `React.memo()` if it isn't already connected.

**Comment by MargaretKrutikova** [comment]
I am just curious, why do you need to use `ReactReduxContext` in your `NotConnected` component, @adaniliuk? I am talking about this line:
```
NotConnected.contextType = ReactReduxContext; 
```
If I remove it in the example with `react-redux v6`, the component no longer rerenders and it works the same way it does with `react-redux v5`. Is there any reason why you would use `contextType` in components that don't need access to the redux state?

I have never needed to use `contextType` myself, so I apologize if I am missing something obvious here :)

**Comment by adaniliuk** [comment]
@MargaretKrutikova you are right, the example doesn't contain the particular examples. I used it only for demonstration purposes. In our real app case, we have HoC component working with the store directly, e.g. getting current state, dispatching custom actions. Both selectors and actions are quite dynamic and it was hard to build something flexible by using just mapState and mapDispatch methods, but that's something that will definitely revise taking into account new React context API and React Redux behavior.
