### ISSUE TITLE
Unexpected usage of `context` prop on connected component

### ISSUE THREAD

**Issue by Shamilik** [reduxjs/react-redux#1139]
**Do you want to request a _feature_ or report a _bug_?**
 Bug/Unexpected behavior

**What is the current behavior?**
When passing `context` prop to connected component, it's replacing original `Context` and `connect()` returning an `undefined`.

**Related code line:**
https://github.com/reduxjs/react-redux/blob/94799efd81323ec07075dc303603b42300e0e034/src/components/connectAdvanced.js#L216

**Example:**
https://codesandbox.io/s/mm039l9q7x

**What is the expected behavior?**
Not use `context` prop or document this behavior.

**Which versions of React, ReactDOM/React Native, Redux, and React-Redux are you using?  Which browser and OS are affected by this issue? Did this work in previous versions of React-Redux?**
Latest

**Comment by wgao19** [comment]
Based on my understanding, v6 allows you to provide a custom context, in which case React-Redux will use your provided context instead of its default one. This allows you to use your own context consumer in your connected components.

You need to pass the same context to both `<Provider />` and your connected components. 

```JavaScript
const MyContext = React.createContext();

// provide to the Provider
<Provider store={store} context={MyContext} />

// provide to all of your connected components
// two ways of doing this:
connect(mapState, mapDispatch, null, { context: MyContext })(MyComponent)
// or
const MyConnectedComponent = connect(mapState, mapDispatch)(MyComponent)
<MyConnectedComponent context={MyContext} />
```

**Comment by markerikson** [comment]
Up through v5, `store` was effectively a "reserved prop name" for the connected wrapper components, as the wrapper interpreted that as "this prop is an alternate Redux store to subscribe to".  Similarly, in v6, `context` is effectively a "reserved prop name", as it's interpreted as "this prop is an alternate React context to read the store state from".

We do need to document this, but this is intentional, and part of the reason for the major version bump.

**Comment by brapifra** [comment]
It should show a more descriptive error though @markerikson @wgao19

**Comment by casdevs** [comment]
I‘ve had the same problem and added PR #1134 that helps if the context prop does not contain a valid react context (as in the codesandbox example given above)
