### ISSUE TITLE
using connect as a decorator happenning a error!

### ISSUE THREAD

**Issue by leeseean** [reduxjs/react-redux#1162]
×
You must pass a component to the function returned by connect. Instead received {"kind":"class","elements":[{"kind":"method","key":"render","placement":"prototype","descriptor":{"writable":true,"configurable":true,"enumerable":false}}]}
▶ 5 stack frames were collapsed.
Module../src/pages/login/Login.jsx
C:/Users/leese/Desktop/xiaoyuanwang/src/pages/login/Login.jsx:12
```
   9 | const mapDispatchToProps = {};
  10 | 
  11 | @connect(mapStateToProps, mapDispatchToProps)
> 12 | class Login extends React.Component {
  13 |     render() {
  14 |         console.log(this.props)
  15 |         return (

**Comment by markerikson** [comment]
We do not recommend using `connect` as a decorator, because the spec is unstable.

Also, this is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out - you'll probably get a better answer faster. Thanks!

**Comment by ramast** [comment]
I had same issue as OP. The problem was that babel wasn't configured properly to process react components or babel config file has wrong name (i.e .babelrc instead of babel.config.json)
