### ISSUE TITLE
Version 7: Connected components are objects instead functions

### ISSUE THREAD

**Issue by radeno** [reduxjs/react-redux#1223]
With react-redux 6 connected component was returned as function. eg:

`ƒ Connect(props)`

Instead version 7 returns it as object because react hooks:

`{$$typeof: Symbol(react.memo), type: ƒ, compare: null, WrappedComponent: ƒ, displayName: "Connect(Component)", …}`

I think this should be noted for developers with PropTypes module for type checking.

**Comment by timdorr** [comment]
This is because [we use React.memo on the component](https://github.com/reduxjs/react-redux/blob/master/src/components/connectAdvanced.js#L410). As a workaround, you can set the `pure` option to false, which comes with a performance penalty.

**Comment by radeno** [comment]
@timdorr We dont have any fontra arguments. But it is breaking change and should be noted

**Comment by markerikson** [comment]
This is not a breaking change to our public APIs.  

As of React 16.6, special component types like `React.memo()` are objects, not functions.  Any code that assumed a React component can _only_ be a function is wrong, and has been wrong since 16.6 came out.

I'll update the release notes accordingly, but this is an incorrect assumption on the part of the other libraries.

**Comment by timdorr** [comment]
We handle this correctly in React Router 5, FWIW.

**Comment by snehil-12** [comment]
bro help me out ,how should i retrive my component from this
