### ISSUE TITLE
mapStateToProps called when component not due to render

### ISSUE THREAD

**Issue by justincrow** [reduxjs/react-redux#1226]
Hi,
I have a conditionally displayed component, based on a value in redux. All components below are `connect`ed.

eg in a wrapper component's render method: 
 ` { (showValueInRedux) ? <ComponentUsingShowValue/> : <EmptyComponent/> }`

`ComponentUsingShowValue` has a `mapStateToProps` that uses redux state that it expects to be there, hence we guard for that with `showValueInRedux` in the wrapper component.

In version 6, `mapStateToProps` in `ComponentUsingShowValue` is only called when that component is due to render.

In version 7, `mapStateToProps` is called even if the wrapping component has switched to choosing `EmptyComponent` due to `showValueInRedux` being false (after having once been true).

This causes an exception in our current code because the redux values that `mapStateToProps` uses ( in the now non-rendered component) are not available.

Please could you clarify this change in behaviour?

**Comment by timdorr** [comment]
We still ensure top-down update ordering. It is one of our biggest challenges with this library. AFAIK, we didn't change this behavior in 7.0.

Can you provide an example of what you're seeing in a Codesandbox? We need a reproducible test case to work with in order to figure out what's going on here.

**Comment by Andrekra** [comment]
I can confirm we're having the same issue (effectively breaking our application when upgrading from v6 to v7)

Here's an simple example (mind the typo's):
```
const shouldRender = WrappedComponent => props => props.shouldRender ? <WrappedComponent {...props} /> : null

const MyComponent = compose(
  connect(state => ({ shouldRender: Boolean(state.page) })),
  shouldRender,
  connect(state => ({ title: state.page.title }))
)(MyBaseComponent)

<MyComponent />

store.dispatch({ type: 'CLEAR_STATE' }) // => Sets state.page to null
```

**Comment by markerikson** [comment]
@Andrekra : as Tim said, it would really help if you can provide a project that reproduces the issue, preferably as a CodeSandbox.

**Comment by iamandrewluca** [comment]
I also encountered this problem after upgrading to `^7.0`.  
After some analysis with my colleague we understood why this happened.  
But did not understood why this was not happened before.  
In our case this is how JavaScript scopes works.

https://codesandbox.io/s/p9mp9rqq4m

**Comment by Andrekra** [comment]
@markerikson Here's an example https://codesandbox.io/s/v629pkllj0

**Comment by MrWolfZ** [comment]
@markerikson I haven't debugged this yet, but just going from the code could the issue be in [this line](https://github.com/reduxjs/react-redux/blob/7402f728c5948cbf01fb07086dcb1ec66968a044/src/components/connectAdvanced.js#L289)?

I think what might be happening is that the `useLayoutEffect` is called before the cleanup function of the nested component's store subscription effect is called, i,e. the nested subscriber is notified before the containing component is properly unmounted.

**Comment by MrWolfZ** [comment]
Alright, `notifyNestedSubs` is definitely called before the child is unmounted. Here's a test case that shows this. For some reason completely unclear to me this test will actually succeed if the _first_ `INC` is dispatched inside `rtl.act`. It seems there is definitely some ordering issue between the effects based on how they are set up.

Also, this test succeeds if we render the child from the start and only hide it. It has to be first hidden, then shown, then hidden again. Therefore I think this is what is happening:

- the parent is rendered and the effects are registered
- the store gets updated
- the child is now getting rendered and the effect (and its cleanup) are registered
- the store gets updated
- since the parent was in the DOM without the child, it's effects are called first before the child is unmounted

I don't know if this is a react issue to be honest, since it feels like this should not happen.

```jsx
it('should not notify nested components after they are unmounted', () => {
  @connect(state => ({ count: state }))
  class Parent extends Component {
    render() {
      return this.props.count === 1 ? <Child /> : null
    }
  }

  const mapStateToProps = jest.fn(state => ({ count: state }))
  @connect(mapStateToProps)
  class Child extends Component {
    render() {
      return <div>{this.props.count}</div>
    }
  }

  const store = createStore((state = 0, action) =>
    action.type === 'INC' ? state + 1 : state
  )
  rtl.render(
    <ProviderMock store={store}>
      <Parent />
    </ProviderMock>
  )

  expect(mapStateToProps).toHaveBeenCalledTimes(0)
  store.dispatch({ type: 'INC' })
  expect(mapStateToProps).toHaveBeenCalledTimes(1)
  store.dispatch({ type: 'INC' })
  expect(mapStateToProps).toHaveBeenCalledTimes(1)
})
```

**Comment by MrWolfZ** [comment]
My analysis above was wrong. 

Scratch all of the above. It is actually a different timing issue. The problem is that the store subscription is created inside `useEffect`. In the sandbox from @andrekra (and the test below) the dispatches are done immediately after another without giving react a chance to execute effects. That means the the order of events is this:

- the parent is rendered and the store is subscribed to
- the store gets updated
- the child is now getting rendered and the store subscription effect is queued up
- the store gets updated again
- the parent gets updated and hides the child
- the queued store subscription effect of the child is executed (which calls `checkForUpdates` immediately and with the latest state that has the second updated already applied)
- the child store subscription effect gets immediately cleaned up

You can see in this [sandbox](https://codesandbox.io/s/jo5w1p72w) how this happens. The second `toggling render` is printed before the child is mounted for the first time.

The proper fix (that passes all tests including the one I posted above) is to use `useIsomorphicLayoutEffect` for setting up the store subscription. I have created a [PR](https://github.com/reduxjs/react-redux/pull/1235) for this.

**Comment by markerikson** [comment]
Yeah, I wondered whether having the store subscription in an async effect was going to cause issues.

**Comment by justincrow** [comment]
We are also experiencing the same issue with 7.0.2. I've tried to re-create with a minimal example in codesandbox, but I cannot get the same error. I'll keep trying.
Please can this be re-opened?

**Comment by MrWolfZ** [comment]
Do any of you that experience this issue use concurrent mode?

@justincrow do you have exactly the same issue, i.e. a non-rendered component's mapState is called? I want to clarify whether this is still a timing issue with unmounting components or something different.

**Comment by iamandrewluca** [comment]
> Do any of you that experience this issue use concurrent mode?

No

With new patch release I still encounter the issue. And the problem it seems to be as I said above
> At first render AppImpl.props.myObject is undefined and TheConsumer.props.render function catches it into scope.

**Comment by justincrow** [comment]
Hi @MrWolfZ ,
Yes, exactly the same issue.
We don't use concurrent mode (that I'm aware of).
mapState is called on a non-rendered component.
I'll try to find some more time to re-create it in the smallest form (our app has deep nesting).
Many thanks.

**Comment by MrWolfZ** [comment]
@iamandrewluca I had a look at your sandbox and the issue is something completely different, since in your case the `mapState` of `AppImpl` is _not_ called, while it should. I am not 100% sure on why it behaves like it does, but it seems to me that he issue is very specific to the use of providers and consumers. You can in fact [reproduce your issue without using a render prop](https://codesandbox.io/s/0pl1nw0qp) (i.e. the problem is not related to capturing an old value in a closure). I believe the cause is that when a provider gets a new value it will not automatically re-render all children, but it walks the component tree to find all components interested in the context. In the sandbox that means the consumer callback is executed, but the containing component is not re-rendered (and therefore its `mapState` is not called).

You have already pointed out a workaround for your sandbox and in mine the workaround would be to simply check if `myOuterObject` has a value. In any case, since it is something unrelated to this issue I recommend that you open a new one.

**Comment by MrWolfZ** [comment]
@justincrow my current theory would be that something like this happens:

- a store update causes a parent component to hide the child (i.e. the parent render is called)
- react does not commit this change to the DOM immediately, but defers it (this should only be possible in concurrent mode as far as I understand, but maybe not?), so the child does not get unmounted
- another store update occurs, and the child is notified, even though it should already be unmounted

**Comment by markerikson** [comment]
If anyone's still seeing this issue, we _really_ need an example project that reproduces the problem.

**Comment by justincrow** [comment]
I've finally managed to re-create the error in codesandbox. 
Please excuse the surplus code, it needs tidying, but it does show that mapStateToProps is called in customerDashboardTab when it is not due to render when using react-redux 7.0.2, but behaves as expected in 6.0.1

https://codesandbox.io/s/z55jvr7nm

**Comment by markerikson** [comment]
@justincrow : cool, thanks.  Can you point to specifically which files are showing the issue, and the exact steps to run in the sandbox to demonstrate that?

**Comment by justincrow** [comment]
When the sandbox runs, you'll see two links, 'Jim' and 'Bob', when you click on them, an initial action is dispatched to clear the id (which is checked to see whether to display the customer dashboard tab), then a timeout is set (to represent network activity) which sets the selected id.
With 7.0.2, you can see in the console logs that mapStateToProps is called in customerDashboardTab, even though the id is undefined and the component should not be rendered.
Switching to 6.0.1, the mapStateToProps is not called, and so does not error.

**Comment by MrWolfZ** [comment]
I made the sandbox [much smaller](https://codesandbox.io/s/5y82q39y2n), so that it is easier to analyze. I need to go to sleep now, and I will only be able to continue on Friday, but maybe somebody else can solve this. Based on my reduced example the issue can only be due to either the timing of the async fetch action in the select inbox thunk or due to a state update occuring inside `componentDidUpdate` in `InboxView`.

**Comment by MrWolfZ** [comment]
I have further minimized the [sandbox](https://codesandbox.io/s/5y82q39y2n) and the problem seems clear now: in certain situations two dispatches just after another will lead to `checkForUpdates` (the store subscription callback) being called twice after another. If the result of the of the second call doesn't change, it will immediately trigger `notifyNestedSubs`. This causes the issue. I will spend some time later today or tomorrow to turn this into a test case and then hopefully come up with a fix (though I don't really have an idea right now how this could be fixed).

**Comment by MrWolfZ** [comment]
I have created a [new issue](https://github.com/reduxjs/react-redux/issues/1262) for this that contains a truly minimal reproduction sandbox. I will shortly create a PR with the repro as a test case and a potential solution.

**Comment by MrWolfZ** [comment]
@justincrow 7.0.3 was just released and your sandbox works correctly with that version. Could you please test it in your app as well and see if there are still issues?

**Comment by justincrow** [comment]
@MrWolfZ Great work - this issue is resolved in our app.
Thank you.
