### ISSUE TITLE
Upgrading from 6.0.1 to 7.0.2 & react-navigation

### ISSUE THREAD

**Issue by alexpchin** [reduxjs/react-redux#1244]
I'm adding this here just because I think other people may also face the same problem...

When upgrading from react-redux 6.0.1 to 7.0.2, I get the error:

<img width="342" alt="Screen Shot 2019-04-17 at 10 52 08" src="https://user-images.githubusercontent.com/40461/56278849-e9ae8880-60fe-11e9-9453-138e822fdd98.png">

Initially, I believed it to be caused by react-navigations' createBottomTabNavigation options:

```js
tabBarComponent: TabBarBottom,
```

Which I changed to:

```js
tabBarComponent: props => <TabBarBottom {...props} />, 
```

However, I'm now getting:

<img width="344" alt="Screen Shot 2019-04-17 at 11 14 31" src="https://user-images.githubusercontent.com/40461/56280407-08fae500-6102-11e9-9d4c-1b75e431d079.png">

I've been debugging this for a while so I thought I'd put it up here in case others faced the same problem.

**Comment by MrWolfZ** [comment]
I think this is not an issue with this library. If you have a look at the quoted part in the first paragraph of the changes section of the [release notes](https://github.com/reduxjs/react-redux/releases/tag/v7.0.1), you see what the issue probably is. I am not familiar with react-navigation, but the issue seems like it might be due to an old version of react-native. Which version are you using?

**Comment by alexpchin** [comment]
Thank you, I thought I would post as the issue happened as I was upgrading from 6.0.1 to 7 and I thought that others may also face the problem. Currently without a solution, I was unsure what the problem was.

> React-Redux version 7 resolves the performance issues that were reported with version 6, and lays the groundwork for us to design and ship a public useRedux()-type Hooks API in a later 7.x release.

The major change for this release is that connect is now implemented using Hooks internally. Because of this, we now require a minimum React version of 16.8.4 or higher.

This release has undergone extensive performance benchmarking, and we're confident that it's the fastest version of React-Redux yet! We've also expanded our test suite to cover a number of additional use cases and scenarios.

Do you mean what version of `react` are you using? I'm using:
 
```
"react": "^16.8.6",
```

As for react-native, I'm using: 

```
"react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
```

**Comment by MrWolfZ** [comment]
I was specifically asking for the react-native version since the error you see isn't caused directly by react-navigation, but by the underlying renderer. Basically, expo 32.0.0 is based on react native 0.57.0, which does not handle memoized components properly. It only does this starting with 0.58.0. Have a look at the [0.58.0 renderer code](https://github.com/facebook/react-native/blob/57ad19758db60992a4d8ab55219d86eb892ac2b0/Libraries/Renderer/oss/ReactNativeRenderer-prod.js#L1897) and compare it with the [0.57.0 renderer code](https://github.com/facebook/react-native/blob/3008c3ccba7ec9b247f8ce40b2c9ef13deafb63f/Libraries/Renderer/oss/ReactNativeRenderer-prod.js#L1884). You can see it is missing the case for memoized components.

I have absolutely no knowledge about expo and how it plays with different react native versions, so I can't tell you how to solve the problem, but you need to see if it is possible to either upgrade the expo version or directly the react native version.

**Comment by alexpchin** [comment]
Thank you for your help so far. The app works ok with react-redux at version 6.0.1. 

To be clear, upgrading from 6.0.1 to 7.0.2 means that the react-native version that expo 32 uses is too low to support `react-redux` because `react-redux` relies on a minimum version of `react-native` of `0.57.5` to support memoized components.

Therefore, in order to use `react-redux` 7.0.2 with expo, it may be advisable to wait until a new version of expo is released? https://expo.canny.io/feature-requests/p/support-react-1680-aka-hooks

Therefore, due to the performance issues of 6.0.1. If you are using expo 32, it is currently advisable to downgrade redux to 5.1.1?

**Comment by timdorr** [comment]
Yep, not a RR problem per se.

**Comment by ide** [comment]
For a little more context: Expo SDK 33 will internally include RN 0.59.5 (+ React 16.8.3), which includes support for Hooks. However, the Metro bundler uses react-proxy, which assumes that components are always functions and leads to errors like "Expected a constructor." (c.f. https://github.com/facebook/react-native/issues/24452).
