### ISSUE TITLE
useDispatch is not a function error

### ISSUE THREAD

**Issue by indunie** [reduxjs/react-redux#1335]
when I import useDispatch as the example below in [https://react-redux.js.org/next/api/hooks](url) , it displayed an error.

Uncaught (in promise) TypeError: (0 , _reactRedux.useDispatch) is not a function.

```

import { bindActionCreators } from 'redux'
import { useDispatch } from 'react-redux'
import { useMemo } from 'react'

export function useActions(actions, deps) {
  const dispatch = useDispatch()
  return useMemo(() => {
    if (Array.isArray(actions)) {
      return actions.map(a => bindActionCreators(a, dispatch))
    }
    return bindActionCreators(actions, dispatch)
  }, deps ? [dispatch, ...deps] : [dispatch])
}
```

In my code
```
const dispatch = useDispatch()
                const incrementCounter = useCallback(
                    () => dispatch({ type: 'DRIVERS_LIST', payload: data.data.drivers }),
                    [dispatch]
                )
```
Can someone please explain the reason. @timdorr

**Comment by markerikson** [comment]
Please make sure you are using React-Redux v7.1.0.

**Comment by indunie** [comment]
no this is v6. I will update. thank you

**Comment by sadek-boufellaga25** [comment]
i got  React-Redux v7.1.3.
still not working , giving me this error :
` Line 36:8:  React Hook useEffect has a missing dependency: 'dispatch'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

**Comment by AhrenFullStop** [comment]
still an issue for me on V7.2.2

`const dispatch = useDispatch()
    const Register = useSelector(state => state.auth)
    const onSubmit = () => {
        if (email && firstName && lastName && mobileNumber) {
            dispatch(RegisterUsers(firstName, lastName, email, mobileNumber, referalCode))
            setError("");
            if (Register.authorized === true) {
                //do stuff
            }
        } else {
            setError("Enter all your details")
        }
        props.navigation.navigate('interest')
    }`

**Comment by Zhang-haohua** [comment]
I have the same issue.

**Comment by markerikson** [comment]
If you're using React-Redux v7.1.0 or higher, and you're having issues, it has to be some kind of a build setup issue, because the hooks _are_ exported and many people are using them.

**Comment by bakdakonusuruz** [comment]
Hi @markerikson, I'm still having this issue. I can get it while using connect . Also, could you please give little bit more detail about "a build setup issue" ?

**Comment by markerikson** [comment]
@bakdakonusuruz whatever error you're seeing with `connect` would be _entirely_ unrelated to this thread. This thread is discussing an issue with the `useDispatch` hook, which is not used inside of `connect`.

By "build setup" issue, I mean a problem with a Webpack config or similar.  As I said above: the React-Redux library works. The hooks are exported. Hundreds of thousands of people are using them. We know that the package itself is correct. Therefore, if you're having a problem, it's something unique to your project setup and how it's being built.

If you or anyone else is seeing a _specific_ problem, please file a _new_ issue with a link to a project that reproduces the error, because we can't do anything based on comments that are just "I'm seeing an error message".
