### ISSUE TITLE
Cannot read property 'isConnected' of undefined redux

### ISSUE THREAD

**Issue by iOSUser110** [reduxjs/react-redux#1356]
**Description**

Cannot read property 'isConnected' of undefined redux

**Current behavior?**
On running react-native application which uses redux,redux-thunk,edux-offline , it returs error with NetInfo.isConnected is undefined with latest version of react-native 0.60.3

**Expected behavior?**
It should work as normal as working on react-native 0.59.8

**Environment**
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Memory: 20.28 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    npm: 6.7.0 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by boozi2** [comment]
Having the same issue, any results ?
