### ISSUE TITLE
Upgrade to latest version introduced componentDidUpdate / DOM issues

### ISSUE THREAD

**Issue by mstange22** [reduxjs/react-redux#1396]
**Do you want to request a _feature_ or report a _bug_?**
Bug (I think - certainly could be a problem with our implementation)

After upgrading from ^5.0.7 to latest (^7.1.1), mostly just to quiet deprecation warnings, I noticed that our message container div in our chat app was not scrolling all of the way to the bottom on new messages.

In `componentDidUpdate()`, we determine if the message count changed and then set `scrollTop` to the `scrollHeight`.  I noticed that `scrollHeight` was no longer changing when a new message was received.  I'm not sure why a change in `react-redux` would alter how `componentDidUpdate()` sees what should be a change to the DOM after `render()`.

Reverting back to ^5.07 solved the issue.

We are using react ^16.3.2, react-dom ^16.3.2 & Chrome 76.0.3809.132.

**Comment by timdorr** [comment]
Can you provide a simplified code example? Codesandbox.io is a good place to set that up.

**Comment by mstange22** [comment]
I built a simple test app and could not repro with 7.1.1: https://codesandbox.io/embed/nice-leavitt-skegl?fontsize=14.

Of course, our system is a lot more complicated (batching messages and rendering loading spinner during fetch, etc.), so something else is causing the issue.  I will debug more on our end and perhaps build out this test case if I can isolate the issue.  Seems to be something in our codebase, but it's odd that the behavior is not seen when we revert back to 5.0.7.

**Comment by mstange22** [comment]
Ok, so I did a bit more troubleshooting, trying to close the gap on the successful test app and our implementation and was able to repro: https://codesandbox.io/embed/nice-leavitt-skegl

I apologize if this is intended behavior in the upgrade, but our `messagesContainer` div is actually inside of a (connected) child component of the component in which I'm inspecting the DOM to determine the scroll height.  `componentDidUpdate()` is not seeing the updated `scrollHeight` of the div inside of the child of the component that just rendered.  On the next render (if you add another message), it gets the previous `scrollHeight`, but appears to always be one behind.

**Comment by ckedar** [comment]
The issue is with sequence in which components gets updated.

Code from repro sandbox has two `connect`ed components - `App` and `ChatMessages`.
`componentDidUpdate` of outer component `App` assumes that child component `ChatMessages` has been updated and hence has already attained a new `scrollHeight`.

This was true in `5.07`, but in `7.1.1` it plays out differently - parent component `App` gets updated first. So when `scrollToBottom` is called, the `ChatMessages` has not yet been updated and hence has not increased in height.

My guess is that this change in behaviour is because of new context/hooks API that is being used.

So looks like the issue is with application code which is dependant on particular sequence of updating the component that was observed in earlier version but was not guaranteed per se.

**Comment by timdorr** [comment]
That's actually a React thing. Check the docs for gSBU: https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate They specifically point out the sync issues relating to direct DOM access (even using scrollHeight as an example).

**Comment by mstange22** [comment]
Thank for the link.  Seems to be an identical use case.  I ended up moving the scrollHeight inspection to the child component.
