### ISSUE TITLE
Should I avoid writing const { a, b, c, d } = useSelector(state  => state)  ?

### ISSUE THREAD

**Issue by ZYinMD** [reduxjs/react-redux#1459]
It's tempting to write `const { a, b, c, d } = useSelector(state  => state) ` sometimes, because it's very concise. Will this cause unnecessary rerender? Or in other words, is it equal to `const state = useSelector(state  => state)` which subscribes to every single change in the store?

Thanks!

**Comment by dai-shi** [comment]
Yes.

If you want that pattern, I suggest you to try an unofficial library [reactive-react-redux](https://github.com/dai-shi/reactive-react-redux) as an experiment.
```js
const { a, b, c, d } = useTrackedState();
```
This works without unnecessary re-renders.

**Comment by markerikson** [comment]
Yes, that will absolutely cause unnecessary re-renders, for two reasons:

- That is over-subscribing to too much data.  A component should only extract the minimal amount of data it needs from the store.
- Since the selector is returning an object, you would need to use the `shallowEqual` comparison function instead of using the default reference comparisons ( https://react-redux.js.org/api/hooks#equality-comparisons-and-updates )

So, please don't do that :)

**Comment by ZYinMD** [comment]
Hi @markerikson, thanks very much for your answer! After reading the docs carefully, I just want to make sure I've understood it correctly: 

So basically this is also not good, right? 

```js
const { a, b, c, d } = useSelector(state => {
  const { a, b, c, d } = state;
  return { a, b, c, d };
})
```
And if I want to do something like this, I should add `shallowEqual` as the second argument, is that right?

Thanks!

**Comment by markerikson** [comment]
This example is halfway better, because it's not just blindly returning all of `state`.  However, yes, as written, it still has the same net bug: it will run every time `state` changes, _and_ it will _always_ cause a re-render by returning a new object reference.  If you were to use `shallowEqual` as the second argument, or replace the contents of the selector function with a memoized selector that only calculates a new result object when one of `a,b,c,d` change, it would be okay.
