### ISSUE TITLE
In the red box, the double arrow function, why is it called once to trigger the 'dispatch' in the second function?

### ISSUE THREAD

**Issue by zhangpengfa666** [reduxjs/react-redux#1490]
![CAE40E39-65BD-43c0-8FA3-8339A5D19FBE](https://user-images.githubusercontent.com/43570454/71815609-fcb51e80-30ba-11ea-9a84-2bdf6ab41bb3.png)

In the red box, the double arrow function, why is it called once to trigger the 'dispatch' in the second function?

**Comment by zhangpengfa666** [comment]
![CAE40E39-65BD-43c0-8FA3-8339A5D19FBE](https://user-images.githubusercontent.com/43570454/71815803-98468f00-30bb-11ea-9d4b-28f41bc74351.png)

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
