### ISSUE TITLE
Upgrade to React 16.13.1 creates a new console warning

### ISSUE THREAD

**Issue by Ethorsen** [reduxjs/react-redux#1560]
React 16.12.0 does not have this warning in place. Everything works smoothly

React 16.13.x introduces a new warning 

https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-1
- Warn when a function component is updated during another component's render phase (@acdlite in #17099)

As soon as we update, we have this warning thrown from connectAdvanced, as described here

- https://github.com/facebook/react/issues/18178#issuecomment-596266655

and here

- https://github.com/facebook/react/issues/18178#issuecomment-600817794

**Comment by timdorr** [comment]
As was stated in the linked issue, the problem doesn't lie in this library, but in how you are using it. Without a code example, I can't show you the error in your code. But everything we do regarding state updates is done within effect hooks, so our part is correct. However, the error may be attributed to our code because of it being a HoC.

**Comment by SanSan-** [comment]
@timdorr 
as example of that code you can see [here](https://github.com/SanSan-/react_quick_start/tree/feature/RQS-4-fetch)

`Auth` component produce this issue: `Cannot update a component ('ConnectFunction') while rendering a different component ('Auth'). To locate the bad setState() call inside 'Auth', follow the stack trace as described in https://fb.me/setstate-in-render` inside `connectAdvanced`.

Can you explain that, please?
