### ISSUE TITLE
Custom context in documents has a error in typescript

### ISSUE THREAD

**Issue by ShmilyLin** [reduxjs/react-redux#1565]
```typescript
export const DirectoryContext = React.createContext(null);
export const useDirectoryStore = createStoreHook(DirectoryContext);
export const useDirectoryDispatch = createDispatchHook(DirectoryContext);
export const useDirectorySelector = createSelectorHook(DirectoryContext);
```

`createStoreHook(DirectoryContext)` has an error:

```
Argument of type 'Context<null>' is not assignable to parameter of type 'Context<ReactReduxContextValue<any, AnyAction>>'.
  The types of 'Provider.propTypes' are incompatible between these types.
    Type 'WeakValidationMap<ProviderProps<null>> | undefined' is not assignable to type 'WeakValidationMap<ProviderProps<ReactReduxContextValue<any, AnyAction>>> | undefined'.
      Type 'WeakValidationMap<ProviderProps<null>>' is not assignable to type 'WeakValidationMap<ProviderProps<ReactReduxContextValue<any, AnyAction>>>'.
        Types of property 'value' are incompatible.
          Type 'Validator<null | undefined> | undefined' is not assignable to type 'Validator<ReactReduxContextValue<any, AnyAction>> | undefined'.
            Type 'Validator<null | undefined>' is not assignable to type 'Validator<ReactReduxContextValue<any, AnyAction>>'.
              Type 'null | undefined' is not assignable to type 'ReactReduxContextValue<any, AnyAction>'.
                Type 'undefined' is not assignable to type 'ReactReduxContextValue<any, AnyAction>'.ts(2345)
```

**Comment by markerikson** [comment]
Two things:

- We don't maintain the TS typings in this repo, they're over in DefinitelyTyped
- Given what we put into context, I would expect that `React.createContext(null)` is indeed invalid, which is what the error is telling you.

**Comment by trblackw** [comment]
@markerikson 
>I would expect that React.createContext(null) is indeed invalid
I would suggest changing the [docs](https://react-redux.js.org/api/hooks#custom-context) then because this is the example context that's used

**Comment by gabrielbezerra81** [comment]
@trblackw Did you find a way to solve this? I could not find a solution.

**Comment by trblackw** [comment]
@gabrielbezerra81 Unfortunately no, I just gave up on trying to inject my context into the store and instead just have separate provider. Ultimately in my case it made more sense to have them separate but regardless the typings could definitely use some improvement around this feature.

**Comment by hemedani** [comment]
I have the same issue.
I want to use redux on monorepo and share some redux logic on separate package.
but with every try i get to new type error.

**Comment by hemedani** [comment]
this code solve the type error but it still has error for wrapping component to redux provider on run time
```typescript
const MyContext = React.createContext(
  {} as ReactReduxContextValue<any, AnyAction>
);
export const useStore = createStoreHook(MyContext);
export const useDispatch = createDispatchHook(MyContext);
export const useSelector = createSelectorHook(MyContext);

```

**Comment by hemedani** [comment]
[please fix this documentation](https://react-redux.js.org/api/hooks#custom-context)

**Comment by ash-r1** [comment]
I met the exact same problem...

@markerikson Excuse me, please reopen this issue.
Also, would you mind if you have a look at this problem?

**Comment by chrisbruford** [comment]
Also hitting this problem having followed [the same docs](https://react-redux.js.org/api/hooks#custom-context)

@markerikson as you say `null` is invalid - what _is_ valid?

**Comment by markerikson** [comment]
So here we get into the issues of distinguishing what is legal _runtime_ behavior, and what is legal _compile-time_ behavior.

The initial value for a React context that you pass to `React.createContext()` will _only_ be used at runtime _if_ you try to consume the context without a corresponding `<MyContext.Provider>` around it.  In practical usage, this almost never happens. So, you can generally get away with defining `createContext(null)`, because that `null` will never be read from a context.

However, TS doesn't know that. TS expects that if you say a context value looks like `{a: number, b: string, c: SomeFancyCallbackType}`, that you _will_ provide an object that looks like that at all times. That includes for the initial value.

In plain JS code, `null` is an entirely acceptable value here.  It's only TS that has to be satisfied.  Therefore, the options are:

- Go through the entire exercise of defining an object that exactly matches the shape of what the context value is supposed to be
- Tell TS to shut up and ignore what you're doing here

Last time I looked, our context looks roughly like `{store, subscription}`.  I haven't looked over at the TS typings in `@types/react-redux` to see if they capture what we actually put into context.  

Therefore, my advice is to take option 2: just tell TS to shut up. Slap a `// @ts-ignore` or an `as unknown as WhateverTheContextTypeIs` on  it.

**Comment by RADesai** [comment]
has anyone figured out how to use this?

**Comment by EskiMojo14** [comment]
Update to this - in v9 we took the opportunity to change the typescript behaviour to match what's happening in runtime. The context instance is typed to hold `ReactReduxContextValue | null`, and the hooks know that they filter out the nulls by throwing an error.

This means that a normal setup should now look something like:
```ts
const context = createContext<ReactReduxContextValue | null>(null);

const useStore: () => AppStore = createStoreHook(context);

const useDispatch: () => AppDispatch = createDispatchHook(context);

const useSelector: TypedUseSelectorHook<RootState> = createSelectorHook(context);
```
Note the type annotations to give your more specific AppStore, AppDispatch, and RootState types.

[Playground link](https://tsplay.dev/mpzLMw)
