### ISSUE TITLE
Connect typescript typing compiles in error

### ISSUE THREAD

**Issue by ctaque** [reduxjs/react-redux#1572]
[Minimal repo](https://bitbucket.org/Syprex/vad-react-redux-bug-minimal-repo/src/master/)

**What is the current behavior?**

I am upgrading to last version of typescript / react / redux / react-redux and I followed the instructions at react-redux.js.org.

I typed my root reducer like so :

```typescript

const test = (state: number = 0, action: any) => ({
    state
});

const rootReducer = combineReducers({
    test
});

export type StoreState = ReturnType<typeof rootReducer>
```

I typed all the return types of the reducers,

This is my store 

```typescript

export default createStore(rootReducer, 0 );

```

I typed my connect function like so : 

```typescript
import { Router } from 'react-router'; 

interface MyStateProps {
    count: number;
}

interface MyOwnProps {

}

   connect<MyStateProps, {}, {}>(
        ({ test }: StoreState): MyStateProps => ({
            count: test
        }),
        null
    )(
```

And I have this compilation Error : 

```typescript
o overload matches this call.
  The last overload gave the following error.
    Argument of type '({ test }: CombinedState<{ test: never; }>) => MyStateProps' is not assignable to parameter of type 'MapStateToPropsParam<MyStateProps, MyOwnProps, DefaultRootState>'.
      Type '({ test }: CombinedState<{ test: never; }>) => MyStateProps' is not assignable to type 'MapStateToPropsFactory<MyStateProps, MyOwnProps, DefaultRootState>'.
        Types of parameters '__0' and 'initialState' are incompatible.
          Type 'DefaultRootState' is not assignable to type 'CombinedState<{ test: never; }>'.
            Property 'test' is missing in type 'DefaultRootState' but required in type '{ test: never; }'.  TS2769

    27 | 
    28 |     export default connect<MyStateProps, MyDispatchProps, MyOwnProps>(
  > 29 |         ({ test }: StoreState): MyStateProps => ({
       |         ^
    30 |             count: test
    31 |         }),
    32 |         (dispatch) => ({ dispatch })
```

**What is the expected behavior?**

I created a new CRA app yesterday and copied the sources from an app of older version of CRA and I am copying the sources. I upgraded to the following version: 

typescript 3.8.3 -> 3.8.3
react 16.13.0 -> 16.13.1
redux 4.0.5 -> 4.0.5
react-redux 6.0.1 -> 7.2.0

There is a major version on react redux but I tried downgrading to 6.0.1 and I have the same error

**Comment by markerikson** [comment]
Your reducer is defining its initial state as a number, but it's then returning an object.  Not sure if that's actually responsible for the issue here, but it may be related.

Note that [we specifically recommend using the `ConnectedProps<T>` technique described in the docs](https://react-redux.js.org/using-react-redux/static-typing#inferring-the-connected-props-automatically) for inferring the props passed from `connect`, rather than explicitly declaring the generic parameters.

Beyond that, the issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!
