### ISSUE TITLE
Keyboard dismissing on store change on React Native

### ISSUE THREAD

**Issue by adomoshe** [reduxjs/react-redux#1582]
**What is the current behavior?**

Hi, thank you for a great package. I hope I am posting this in the right place, it may be a Redux or React Native problem or a mismatch of my packages.

My problem is that whenever a part of the state that I am subscribed to updates, my TextInput loses focus and the keyboard dimisses. The problem used to be much worse when I was destructuring part of state coming back from `useSelector`. Switching to a selector for each specific value I need greatly alleviated this problem (and I'm sure helped my overall performance), but did not solve it.

I am using the useSelector and useDispatch hooks throughout the whole app without dedicated HOCs.
These are the relevant packages that I am using
``` "react": "16.8.6",
    "react-native": "0.60.5",
    "react-redux": "^7.2.0",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0"
```

**What is the expected behavior?**

That like the `useState` hook, the component will re-render but not dismiss my keyboard.

Thank you for any help, and please let me know if this issue would be be more helpful posted on one of the other packages.

**Comment by timdorr** [comment]
This doesn't have anything to do with React Redux by itself. It's really more of a usage issue of how you're retaining components. I would post a more concrete example with source code on Stack Overflow or Reactiflux.

**Comment by rpramono** [comment]
Yes, I found have this issue as well. And in my case it's because I'm using lodash debounce, which I put inside a React.useCallback method (to make the debounce method persist). Redux itself is not a problem, but when the debounced method triggers, the keyboard will be hidden.

I don't want to call redux dispatch directly, as I want to have better performance (by debouncing).. Any idea on how to fix this?

Here is my code:

`const saveNoteRef = React.useRef()`
`    saveNoteRef.current = (row) => updateNote(row);`
`    const debouncedSaveNote = React.useCallback(_.debounce(`
`        (...args) => saveNoteRef.current(...args),`
`        500,`
`    ), []);`
