### ISSUE TITLE
typescriptError: (0 , _reactRedux.connect) is not a function

### ISSUE THREAD

**Issue by karanbht507** [reduxjs/react-redux#1624]
Hi I am using jest and enzyme for unit testing and in this when I run test cases getting this error in login container. Login container is connected with connect. 

Here is the complete error-
TypeError: (0 , _reactRedux.connect) is not a function

      101 | };
      102 | 
    > 103 | export default connect(({ login, loading }: ConnectState) => ({
          |                ^
      104 |   userLogin: login,
      105 |   submitting: loading.effects['login/login'],
      106 | }))(Login);

      at Object.<anonymous> (src/pages/user/login/index.tsx:103:16)
      at Object.<anonymous> (src/pages/user/login/login.test.js:6:1)

And here is the test file

import { shallow, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });

describe('Login component tests', () => {
  let wrapper = shallow(
    <LoginContainer.WrappedComponent userLogin={{ status: '', message: '' }} />,
  );
})

Thanks for help in advance

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
