### ISSUE TITLE
"Cannot update a component while rendering a different component" warning caused by `useSelector`

### ISSUE THREAD

**Issue by mdreyer** [reduxjs/react-redux#1640]
using **react 16.13.1** and **react-redux 7.2.1** I get this new "cannot update a component while rendering a different component" react warning in the following scenario:

1) a parent component pulls from some redux slice with `useSelector`
2) a child of that parent also pulls from the same redux slice with `useSelector` (can be the same or a different value of that slice)
3) the parent dispatches an action that updates that redux slice

=> 💥 I get the warning on the console "Warning: Cannot update a component (SomeChild) while rendering a different component (SomeParent). To locate the bad setState() call inside SomeParent, follow the stack trace..."

if my implementation is an antipattern, what's the expected pattern? that parents should be aware if _any_ of their children want to access the same redux slice as them, and if so pull the value for them and drill it down to the appropriate child?

**Comment by markerikson** [comment]
The issue only occurs if you are actually queuing state updates _while rendering_, which is not allowed in React in general.

For background on the specific React behavior here, see https://github.com/facebook/react/issues/18178 .

I'd recommend looking at `SomeChild`'s render logic, and find a place where you're dispatching an action outside of a click handler or a `useEffect`, directly in the body of the render logic.  Changing that code to _not_ dispatch while rendering should fix the issue.

**Comment by mdreyer** [comment]
ah, guess I was under the impression that the hook would queue the update for after the render, but obvisouly not the case

so only change state (`useDispatch`, `setState`) in an event handler or a `useEffect` hook, roger that

**Comment by markerikson** [comment]
Yeah, queueing state updates in the middle of rendering has always been effectively disallowed in React.

The _only_ exception to that is [the extremely rare case of mimicking `getDerivedStateFromProps` in a function component](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops).  If you do queue a state update in the body of a function component, React will immediately re-render that component and apply the state update.  But, you still cannot queue updates for _other_ components that way.

**Comment by giseleml** [comment]
Hello! My application works literally the same but I am having the same issue even though my parent component's dispatch function is already being called inside of an useEffect. I would appreciate if anybody could help with ideas.

Parent
```
function Startup() {
  useInjectSaga({ key: 'startupSaga', saga });
  useInjectReducer({ key: 'login', reducer: loginReducer });
  useInjectSaga({ key: 'login', saga: loginSaga });

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(doStartup());
  });

  return null;
}
```
The doStartup dispatches a call to the `login` reducer that is inside of the child component:
```
export const initialState = {
  isLoggedIn: false,
};

const loginSlice = createSlice({
  name: 'login',
  initialState,
  reducers: {
    login(state) {
      state.isLoggedIn = true;
    },
  },
});
```
Then on any child component that I use its selector to get the value of `isLoggedIn`, I get the "Cannot update a component while rendering a different component" warning. That only happens when the value actually changes from true to false or vice-versa.
```
  const { isLoggedIn } = useSelector(selectLogin);
```

For some reason, another child component was also bringing up the same error with its own child components but I was able to get rid of it using `shallowEqual`. Although it still throws an error for the Parent component I showed above. 

```
  const { isLoggedIn } = useSelector(selectLogin, shallowEqual);
```

Sadly that is not the solution for the Parent/Child situation.
If anyone could take a look and give me some idea of what's going on it would be great and I would be very thankful. I spent the whole day on this and didn't come up with a reason why :disappointed: 

Ps: My react/react-dom versions are 17.0.1

**Comment by Bharateshwar** [comment]
Hey @giseleml, I am in a very similar solution as you described above.
Have your found any solution?
I noticed it comes up if we use the useSelector hook. Even in the console hints to that. 🥲

**Comment by markerikson** [comment]
@Bharateshwar as per above: the issue is _not_ `useSelector` - the issue is _triggering state updates while rendering_, such as dispatching a Redux action.

**Comment by Bharateshwar** [comment]
@markerikson shouldn't this be taken care of if the action is dispatched within a useEffect? 🙁

**Comment by markerikson** [comment]
@Bharateshwar My guess is that the `useInjectReducer` hook or one of the others is causing a dispatch while rendering, but there's not enough info to be sure.

**Comment by julienw** [comment]
The new react docs are now advising to change the state while rendering (see https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes), but only for the same component. So if I understand properly this doesn't apply to Redux because when a part of a Redux state changes, all connected components will rerender with the current recommended hook-based programming. (I believe this could be OK with old-style connected components that do memoization and do not render if no value change).
Is my understanding correct?

**Comment by markerikson** [comment]
@julienw correct. You can do a `setState` to update the _current_ component, in which case React will immediately apply the update and re-render synchronously after this component call returns.  But you can't update _other_ components while rendering:

- https://blog.isquaredsoftware.com/2020/05/blogged-answers-a-mostly-complete-guide-to-react-rendering-behavior/#setting-state-while-rendering

**Comment by dvaldivia** [comment]
I only encountered this issue when moving from a slice and using the selected value inside a `useEffect` to replacing the slice with the result of an RTK Query

# Original 

This used to work

```typescript
const sessionState = useSelector(
     (state: RootState) => state.session.sessionState,
   );
useEffect(() => {
     if (sessionState === "valid") {
       dispatch({ type: "socket/OBConnect", siteId, namespace, resourceId });
     }
   }, [dispatch, sessionState, siteId, namespace, resourceId]);
```

# Version with the problem
```typescript
const { data: globalSession, isError: globalSessionInError } =
    useSessionCheckQuery();

 useEffect(() => {
     if (!globalSessionInError && globalSession) {
       dispatch({ type: "socket/OBConnect", siteId, namespace, resourceId });
     }
   }, [
     dispatch,
     globalSession,
     globalSessionInError,
     siteId,
     namespace,
     resourceId,
   ]);
```

the problem here is that maybe the RTK Query is causing a re-render while the component is already rendering and the dispatch is happening, I suspect the only alternative is to return the slice to keep track of the state, but that would create two places for keeping the same state
