### ISSUE TITLE
Types of parameters 'props' and 'props' are incompatible.

### ISSUE THREAD

**Issue by tomaszs** [reduxjs/react-redux#1643]
There is no @types/react-redux for react-redux 7.2.0 and higher.
Probably this is the cause for the error:

Types of parameters 'props' and 'props' are incompatible.

**Comment by markerikson** [comment]
I don't know what error you're referring to here, because you haven't provided any code or the actual error.

We don't maintain the React-Redux TS typings ourselves - those are kept in Definitely Typed.  Also, the current `@types/react-redux` package covers our API correctly, including the v7.2.1 release.
