### ISSUE TITLE
Could not find react-redux context value

### ISSUE THREAD

**Issue by iBobo5** [reduxjs/react-redux#1677]
Hello everyone!
I'm trying to doing my exportable package in which I create the redux store.
The entry point of my package component expects an application given from another project. Here's the code of the package:

 ```
<Provider store={store}>
      <IntlProvider messages={messages} locale={locale} defaultLocale={config.defaultLanguage}>
     {app}
    </IntlProvider>
</Provider>
```

The package entry point is this:
`<MyCore withLogs={false} applicationSagas={appSagas} applicationReducers={appReducers} app={<App />} />`

Ok. If I use the following code inside my package code and I use useSelector or useDispatch everythings works fine, but if I use the same code in an external project (obviusly after installed my package) I encounter this error:

`useDispatch() Error: Could not find react-redux context value; please ensure the component is wrapped in a <Provider>`

How can I solve this and use store outside the package code?
Thanks in advance
Matthew

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use [our Discussions page](https://github.com/reduxjs/react-redux/discussions?discussions_q=category%3AHelp), [Stack Overflow](https://stackoverflow.com/questions/tagged/redux), or [Reactiflux](https://www.reactiflux.com/) where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
