### ISSUE TITLE
`TypedUseSelectorHook` is deprecated but official documentation still recommends using it

### ISSUE THREAD

**Issue by wesm87** [reduxjs/react-redux#1678]
The [Static Typing](https://react-redux.js.org/using-react-redux/static-typing#typing-the-useselector-hook) documentation refers to the `TypedUseSelectorHook` helper type, but if you import it from `@types/react-redux` and hover over the import in VSCode, it's marked as deprecated and you're instructed to use `createSelectorHook<State, Action>()` instead. I can submit a PR to update this if needed.

**Comment by markerikson** [comment]
We already got a PR merged into DefinitelyTyped to un-deprecate that :)  Please update your `@types/react-redux` version.

**Comment by ldco2016** [comment]
@markerikson , does this apply to version 7.2.2?

**Comment by markerikson** [comment]
@ldco2016 not quite sure what you're asking. The problem wasn't with the React-Redux library itself - it was with the `@types/react-redux` package. I'm not sure what the version numbering is for that, but please update it to the latest version and you should be good.

**Comment by ldco2016** [comment]
@markerikson , so I had put this together inside my `use-typed-selector.ts` file:

```typescript
import { useSelector, TypedUseSelectorHook } from "react-redux";
import { RootState } from "../state";

export const useTypedSelector: TypedUseSelectorHook<RootState> = useSelector;
```

Until a colleague shared with me that `TypedUseSelectorHook` is deprecated, but notice I am using `react-redux` library and not `@types/react-redux` library. So in which library is `TypedUseSelectorHook` deprecated? 

So I do have in my `package.json` file both:

`"@types/react-redux": "7.1.15",`

and 

`"react-redux": "7.2.2",`

So is `TypedUseSelectorHook` deprecated for my case?

**Comment by markerikson** [comment]
The whole point of this is that `TypedUseSelectorHook` was _never_ actually deprecated. Someone in the community filed a PR to mark it as deprecated in the types package, but that was _not_ something we ever suggested or encouraged.  So when we saw that a new types version was released with that deprecation, we filed a new PR to _remove_ that deprecation.

So. **`TypedUseSelectorHook` is _not_ deprecated, and never was deprecated, and you _should_ use it as we show.**

**Comment by ldco2016** [comment]
@markerikson , awesome, thats where the confusion lies. My colleague thinks its deprecated, but from reading this very issue that he himself shared with me, it seemed the other way around.

Thank you.

**Comment by markerikson** [comment]
Sure.

Purely as background, I _think_ what happened was:

- Our `useSelector` and `useDispatch` hooks rely on the singleton `ReactReduxContext` in our own library, as does `connect`
- Some users pointed out that while `connect` allowed passing a custom context instance as a prop, there was no way to use a custom context instance with the hooks
- We released new `createSelectorHook` and `createDispatchHook` APIs whose _only_ purpose is to allow users to create a customized version of `useSelector` and `useDispatch` with their own custom context instance instead of `ReactReduxContext`
- Some user out there saw those, and assumed that they were meant for a broader use case, like "create a general-purpose customized version of these hooks", which is not correct
- They decided to update the `@types/react-redux` package based on this wrong assumption
