### ISSUE TITLE
TypeScript errors after installing 7.2.3 relating to @types/react-redux now being a "dependency"

### ISSUE THREAD

**Issue by marchaos** [reduxjs/react-redux#1700]
After installing 7.2.3, our build failed due to TS error pertaining to duplicate declarations. (see below). We've seen this before and I tracked it down to the release of react-redux last night. We initially had `@types/react-redux` in our package.json, which has since been removed, but the errors were still present. Due of the sub dependency of `@types/react` being 17.0.3 in react-redux, 
and our explicit `@types/react` being `16.14.5`, `@types/react` is not deduped. If we upgrade to `17.0.3` as well, then we no longer get errors, but this is forcing us to have a miss-match between our react version and the `@types/react` version. 

It's questionable as to whether 7.2.3 supports react 16 because of this. Maybe this is a known issue and the action described above is what you'd expect? 

TS Errors for reference for others:
```
node_modules/@types/react-redux/node_modules/@types/react/index.d.ts:2976:14 - error TS2300: Duplicate identifier 'LibraryManagedAttributes'.

2976         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                  ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@types/react/index.d.ts:2977:14
    2977         type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    'LibraryManagedAttributes' was also declared here.

node_modules/@types/react-redux/node_modules/@types/react/index.d.ts:2987:13 - error TS2717: Subsequent property declarations must have the same type.
```

**Comment by markerikson** [comment]
Hmm. That's a good point. I just grabbed the latest `@types/react-redux` when I made that change.

I'm not clear on how `@types/react-redux` and `@types/react` are versioned, and how those versions related to React versions.  

I'm unfortunately busy with my day job atm.  Can you do me a favor and put together a couple examples of how things behave with 7.2.3 and differing versions of React and the types?

**Comment by timdorr** [comment]
Should the `@types/` packages be peer deps instead of regular deps?

**Comment by markerikson** [comment]
The intent of the change was to _force_ that `@types/react-redux` gets installed automatically, so that users don't ever forget to add it.  I know NPM 7 does something different with peer deps now, but NPM 6 and Yarn don't install them.

If this turns out to have been a really bad idea we can definitely backtrack, but I'd like to get more info on exactly what scenarios are busted here.

**Comment by marchaos** [comment]
@markerikson From what I can see, the latest 16.x and 17.x of the @types/react and @types/react-redux are compatible (i.e no TS errors) and similarly, react 16 and and 7.2.3 react-redux are ok too (besides the TS errors). Our main blocker for upgrading to react 17 is enzyme not being compatible, so for now, we've gone back to 7.2.2.

**Comment by chrisbutler** [comment]
we are in the same situation as @marchaos. i was also surprised to find the types inclusion in a minor version bump, given that it causes TS errors and has the potential to break build processes

**Comment by markerikson** [comment]
Two quick thoughts:

- Given how TS works and its own lack of semantic versioning, seemingly _any_ change to _anything_ types related could hypothetically cause breakage somewhere
- I made the change to auto-depend on the types because we've repeatedly seen people forget to install them, so I figured this would simplify things for most people. First I knew that there were any potential problems with that approach was seeing this issue filed. 

So far no one has provided additional information indicating what a specific problem might be with regards to types versions compatibility, and my focus has been finalizing our RTK Query package and merging it into Redux Toolkit.  So, no, it hasn't been on my radar.

If this is still an active problem for people, I need more info about what sorts of actual interactions cause these errors - combinations of package versions, etc.

**Comment by julienw** [comment]
I'd like to add that `@types/react-redux` [depends itself on `redux`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/25a17e04a81dd5bb9b97b3cec89d14af45926674/types/react-redux/package.json#L6), so this fails the goal of `we've completely dropped the dependency on Redux` as stated in the latest changelog.

**Comment by markerikson** [comment]
Hmm. Hadn't thought about that part, but we did at least eliminate the use of Redux as a runtime dependency.

**Comment by julienw** [comment]
> Hmm. Hadn't thought about that part, but we did at least eliminate the use of Redux as a runtime dependency.

mmm, but did you really? :-)

The entry `@types/react-redux` is in `dependencies` not `devDependencies` see:
https://github.com/reduxjs/react-redux/blob/86e962edf8ed077cf720e8e089876227d943dfe8/package.json#L49-L56

Similarly for the @types/react-redux types (probably right here):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/813a8799e465a7d5f0d6776643f20f93681e85e4/types/react-redux/package.json#L3-L7

(To be clear, I don't think _this_ is a huge problem, after all `redux` is needed to use `react-redux` at one point -- but this may cause issues in the future if/when redux changes its major version).

**Comment by gugu** [comment]
> (To be clear, I don't think this is a huge problem, after all redux is needed to use react-redux at one point -- but this may cause issues in the future if/when redux changes its major version).

redux changed their minor version and now @types/react-redux installs redux@4.0.0 and my code installs redux@4.1.0. What do you think about including d.ts files in this repo instead? (I don't plan to describe what do I think about DefinitelyTyped monorepo because it definitely violates Code of Conduct). I can create a PR with these changes

**Comment by julienw** [comment]
> redux changed their minor version and now @types/react-redux installs redux@4.0.0 and my code installs redux@4.1.0. 

This is true, but on my project, this results in installing redux 4.1 for both, as redux 4.1 fulfills `redux@^4.0.0`. But we're deduplicating systematically, so this might be different if you don't. (also that's why I mentioned the major version)

That said I think your proposal makes sense, especially if the maintainers of the project also maintain these types.

**Comment by gugu** [comment]
#1717

**Comment by markerikson** [comment]
Thing is, we _don't_ maintain the React-Redux types ourselves. The community has always done so.  That's why they lived in DefinitelyTyped instead of in this repo.

We did add myself and Lenz to the "list of maintainers for these types" in DTS recently because someone else had filed a PR that marked one of the types as `deprecated` incorrectly without ever consulting us about the intended usage, so we want to be notified in case anyone ever tries to make unwanted changes like that in the future. But, we haven't actually worked on the types ourselves.

When we get around to working on React-Redux v8, we'll rewrite the library in TS. Until then, the types can stay where they are.

**Comment by markerikson** [comment]
Given that React-Redux v8 will be out shortly, and is written directly in TS, I think this can be closed as OBE.
