### ISSUE TITLE
what different form this two case in reat-redux v7.2.3

### ISSUE THREAD

**Issue by oldturkey** [reduxjs/react-redux#1708]
1. export default Form.create()(connect(mapStateToProps)(DynamicFieldSet));   //wrong

2.export default connect(mapStateToProps)(Form.create()(DynamicFieldSet));     

this first case in react-redux V5.0.4, the props `wrappedComponentRef` in wrapperComponment is work great,
but after i upgrade react-redux to V7.2.3, `wrappedComponentRef` is undefined in first case ,it can work in second case .

can you help me ,what happend in this problem.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use [our Discussions page](https://github.com/reduxjs/redux/discussions?discussions_q=category%3AHelp), [Stack Overflow](https://stackoverflow.com/questions/tagged/redux), or [Reactiflux](https://www.reactiflux.com/) where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
