### ISSUE TITLE
[v8] Investigate updating the React-Redux benchmarks repo

### ISSUE THREAD

**Issue by markerikson** [reduxjs/react-redux#1763]
Background: #1740 

After v6 turned out to be too slow, we wanted v7 to be really fast.  I ended up creating a React-Redux benchmarks repo at **https://github.com/reduxjs/react-redux-benchmarks** , which has some stress tests for creating large trees in various scenarios, and dispatching many actions quickly.  It then tries to measure number of re-renders and raw update FPS as a proxy for performance.

I haven't touched that repo since early 2019.  I'd appreciate it if someone could look over that repo and see what might need to be done to prepare things for working with React 18 and some React-Redux v8 alphas.

It would also be good if we can figure out more stats to record in comparison, and maybe better proxies for performance than FPS.

**Comment by ryota-murakami** [comment]
@markerikson Since Looking [npm trends](https://www.npmtrends.com/) search result, I confirmed `Recoil` doesn't getting a constant user rate.

<img width="988" alt="Screen Shot 2021-07-09 at 11 07 05" src="https://user-images.githubusercontent.com/5501268/125012896-e324d680-e0a5-11eb-92fb-c9909390a3eb.png">

So I decide migrate `Recoil` to 'Redux Toolkit' as an one of acceptable de facto standard State Management library, in this project.  

**[Create React App TypeScript Todo Example 2021](https://github.com/laststance/create-react-app-typescript-todo-example-2021)**

I'll rewrite this weekend and I'd like this to be used for benchmarking purposes if that is helpful for your sake.

**Comment by markerikson** [comment]
@ryota-murakami FWIW, for this issue I'm specifically interested in looking at the https://github.com/reduxjs/react-redux-benchmarks and seeing what needs to be done to get ready for updated performance testing with React-Redux v8 and React 18.  Like, obviously some packages will need to be updated, but also I don't remember how the `useSelector` perf tests ended up being defined, or if they cover all the same scenarios that the `connect` tests do.  I also want to see if we can improve how we're measuring "performance" here.

If you or anyone else comes up with additional benchmarks that would be useful too, but my main goal here is just the existing benchmarks repo.

**Comment by ryota-murakami** [comment]
@markerikson I see. I guess @dai-shi has some resource like that...

**Comment by dai-shi** [comment]
Well, https://github.com/reduxjs/react-redux-benchmarks/pull/26 is my last work there. It should be easy to remove r-r-r, but the changes are still too big and duplicated.

If someone is gonna work on this, they can do a better way, because what we want to compare is r-r v7 and r-r v8 and comparing with `connect` is not primary.

**Comment by alk-mandrianarijaona** [comment]
Hello here, I am really interested in subjects around performance so I would love to give this a try. I will first take a look at https://github.com/reduxjs/react-redux-benchmarks to see how it works

**Comment by markerikson** [comment]
@alk-mandrianarijaona cool. FYI, I actually did a major update since posting this issue, to redo the build setup entirely and make it easier to add scenarios:

- https://github.com/reduxjs/react-redux-benchmarks/pull/28
- https://github.com/reduxjs/react-redux-benchmarks/pull/29
- https://github.com/reduxjs/react-redux-benchmarks/pull/30

**Comment by alk-mandrianarijaona** [comment]
@markerikson thanks for that, so what are the next steps you suggest I should look into?

**Comment by markerikson** [comment]
@alk-mandrianarijaona : I just merged the one open PR I had over there .  I think the next steps would be to update the React and React-Redux deps to use the latest React 18 and React-Redux v8 alphas, and then try to add more hooks-based equivalents of the existing `connect`-based usage scenarios.
