### ISSUE TITLE
using useTransition, Suspense , SuspenseList with redux state

### ISSUE THREAD

**Issue by abdoutech93** [reduxjs/react-redux#1797]
### What is the new or updated feature that you are suggesting?

In Concurrent Mode, it important to permit the use of the new features on react 18 such as startTransition and suspense for deffered loading and also the new component SuspenseList to improve performance and the app loading. 

Calling startTransition with redux state causes an exception startTransition is not a function

### Why should this feature be included?

In my case my home page contains a lot of data, so the loading is slow and the UI is not as smooth as it should be during  the loading even if the component is loaded but because the entire page is not fully loaded yet is not possible to click and navigate on the page and this is because of state changes.

### What docs changes are needed to explain this?

adding all this to docs allows people using redux to using this feature.

**Comment by markerikson** [comment]
It's not clear what you're actually suggesting here. Can you clarify the question, and ideally provide a CodeSandbox that demonstrates what you're seeing?

Note that React-Redux v7 is not considered Concurrent/Suspense-compatible - see #1740 and #1732 for discussion.

**Comment by abdoutech93** [comment]
A practical case is that I'm using React-Redux 7 and React 18 with connect. to improve my app performance I'm trying Suspense but I'm getting some runtime exceptions like : startTransition is not a function.
So, if I suppose that suspence and startTransition are some of the major changes on react 18, I suggest to avoid this issues in ordre to allow to people to use it with redux.

**Comment by markerikson** [comment]
Like I just said, React-Redux v7 is not ready for use with React 18. The basic behavior should be passable, but we definitely haven't done anything to try to check its behavior with `useTransition`.

There's no point in adding warnings to the docs yet, because React 18 isn't out and won't be out for a while and it's still very clearly labeled as "Experimental/Alpha".

Glancing at the sandbox, I think your sandbox code is buggy. It's assuming that `useTransition` returns `[startTransition, isPending]`, but the React team recently switched the ordering to be `[isPending, startTransition]` for consistency with the other hooks:

https://github.com/facebook/react/pull/20976

Change your code to be `const [t, isPending] = React.useTransition()` and that error should go away - this part has nothing to do with Redux.

**Comment by markerikson** [comment]
Closing because I think this was a bug with the original sandbox.

**Comment by phryneas** [comment]
@hdlion react-redux 8 with Redux 18 support is out for quite a while by now.

**Comment by hdlion** [comment]
I'm getting error while using suspense and redux.

`Uncaught Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.`

Because component state is going to update and render function is called. I have used a component in side render function which is using suspense so It is getting update in suspense.

How could I stop to send an update to child component which is using suspense.

**Comment by markerikson** [comment]
@hdlion if you're seeing problems, please put together a CodeSandbox, Github repo, or Replay ( https://replay.io/record-bugs ) that actually shows the problem happening and file a new issue.

**Comment by sachTyagi** [comment]
I am facing the similar issue. 

Uncaught Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

Tried <Provider store={store} serverState={initialState} /> on client side. Any suggestions ? @markerikson
