### ISSUE TITLE
Exporting a library store # Not working

### ISSUE THREAD

**Issue by anj-kr** [reduxjs/react-redux#1848]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

React: 16.13.1
ReactDOM: 17.0.2
Redux:4.0.5
React Redux: 7.2.0

### What is the current behavior?

Hello,

We are using a library where it handles authentication and the value of JWT is available in react library store. Now when we use the react library in another react application, we are not able to see the library store values(Only default value) is available in the react application.

I tried with exporting the store directly with respect to react library but nothing seems to working.

My question is - Is it possible to use another react library store with updated value in any other react application?
Tried this as well - https://daveceddia.com/access-redux-store-outside-react/ but only default values are popping up with respect to react custom library and store. Any ideas ? Thank you!

### What is the expected behavior?

Able to use the same store from react library and use it with another react application for fetching the user data

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use [our Discussions page](https://github.com/reduxjs/redux/discussions?discussions_q=category%3AHelp), [Stack Overflow](https://stackoverflow.com/questions/tagged/redux), or [Reactiflux](https://www.reactiflux.com/) where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
