### ISSUE TITLE
TypeScript error when upgrading to react-redux 8.0.0

### ISSUE THREAD

**Issue by atomrc** [reduxjs/react-redux#1909]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 16.14.0
- ReactDOM/React Native: 16.14.0
- Redux: 4.2.0
- React Redux: 8.0.0

### What is the current behavior?

When compiling a TypeScript project that has the `noImplicitAny` config set to `true`, then react-redux `.ts` files are typechecked and result in a compilation error 

```
node_modules/react-redux/src/utils/Subscription.ts:95:8 - error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any[]' return type.

95   get: () => [],
          ~~~~~~~~


Found 1 error in node_modules/react-redux/src/utils/Subscription.ts:95
```

I believe the `ts` files should be stripped from the final bundle that is uploaded to npm in order to avoid such ts config mismatch.

### What is the expected behavior?

There shouldn't be any compilation error. 

### Which browser and OS are affected by this issue?

N/A

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by phryneas** [comment]
All the redux-libraries are shipping with the source code - RTK is also already shipping since 1.0 with TypeScript. 
You should not really have your bundler check files in your node_modules folder (TypeScript will per default only import `.d.ts` files from node_modules, not `.ts` ones unless you explicitly reference them) - did you maybe just include a wrong file?

**Comment by vicrep** [comment]
I'm encountering the same issue and do not think this is a TSC misconfiguration, and the error occurs even when explicitly ignoring node modules.

I ran `--traceResolution` on TSC and that helped me narrow down what I think the issue is:
https://github.com/reduxjs/react-redux/blob/26ddc6a6fc1238408ae5a0cbc18f15be225786dc/src/exports.ts#L30 re-exports `Subscription` directly from SRC (as opposed to relative), which means that the following is then emitted in the type def for `exports.d.ts`

```ts
import type { Subscription } from '../src/utils/Subscription';
```

Which is why this error is occurring, as confirmed by trace resolver:
```
======== Resolving module '../src/utils/Subscription' from '[root]/node_modules/react-redux/es/exports.d.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module as file / folder, candidate module location '[root]/node_modules/react-redux/src/utils/Subscription', target file type 'TypeScript'.
File '[root]/node_modules/react-redux/src/utils/Subscription.ts' exist - use it as a name resolution result.
```

**Comment by vicrep** [comment]
PR to fix here: https://github.com/reduxjs/react-redux/pull/1910

**Comment by markerikson** [comment]
Live in https://github.com/reduxjs/react-redux/releases/tag/v8.0.1 .

**Comment by atomrc** [comment]
Thanks guys for your reactivity 🙏

**Comment by Dammmien** [comment]
That was fast 🚀  !!
Thanks 🙏🏻
