### ISSUE TITLE
Module parse failed: Unexpected token 

### ISSUE THREAD

**Issue by kukovisuals** [reduxjs/react-redux#1931]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React:  18.0.15
- ReactDOM/React Native: 18.0.6 
- @reduxjs/toolkit: "^1.8.3",
- Redux: 4.2.0
- React Redux: 8.0.2

### What is the current behavior?

Module parse failed: Unexpected token (10:12)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.

![image](https://user-images.githubusercontent.com/15222073/179041278-ea058705-613b-461e-8463-6ec1d7d33020.png)

### What is the expected behavior?

I'm sure this is something simple, I have 2 months experience with typescript. Idk if is the tsconfig.json or webpack.config

`npm start` works fine

### Which browser and OS are affected by this issue?

windows 11 AMD razer

### Did this work in previous versions of React Redux?

- [X] Yes

**Comment by markerikson** [comment]
This appears to be an issue with your own application code and build setup, rather than React-Redux. You need to actually compile your app code with Babel or TypeScript to turn that JSX syntax into plain JS.

See https://www.robinwieruch.de/webpack-babel-setup-tutorial/ and https://www.taniarascia.com/how-to-use-webpack/ for a couple good articles on how to do this.

**Comment by kukovisuals** [comment]
I think is something in the tsconfig file but I have no idea what it is

**Comment by phryneas** [comment]
This has nothing to do with Redux, your setup is not able to handle `<Jsx>`.
