### ISSUE TITLE
Definition of the store constant on quick start isn't clear or missing

### ISSUE THREAD

**Issue by je34429** [reduxjs/react-redux#1937]
### What is the new or updated feature that you are suggesting?

the quick start guide suggests the following for creating the store:
```
import { configureStore } from '@reduxjs/toolkit'

export default configureStore({
  reducer: {},
})
```

I'm not sure but every time I install redux tool-kit using js I have to change that snippet into this:
```
import { configureStore } from '@reduxjs/toolkit'

export const store = configureStore({
  reducer: {},
})

export default store;
```

hope this helps

### Why should this feature be included?

To make the quick start guide easier to use for newcomers

### What docs changes are needed to explain this?

just an update on:
https://react-redux.js.org/tutorials/quick-start

change this:
```
import { configureStore } from '@reduxjs/toolkit'

export default configureStore({
  reducer: {},
})
```

to this:
```
import { configureStore } from '@reduxjs/toolkit'

export const store = configureStore({
  reducer: {},
})

export default store;
```

**Comment by markerikson** [comment]
I'm not quite clear what you're suggesting here.  Can you clarify the difference in intent and explanation?  Is it about named vs default exports, or temporarily assigning to a variable before doing the default export?

**Comment by je34429** [comment]
yeah, I suggest temporarily assigning configureStore to a variable before doing the default export.

Then when the import gets called in the next step it would actually work with no additional actions rather than copy and paste the code:
`import store from './app/store'`

**Comment by markerikson** [comment]
I'm a bit confused, actually :)  the line `import store from './app/store'` will work either way, because in both cases the store instance is the default export from the other file.  There is no difference in behavior here.

**Comment by je34429** [comment]
not sure about that, when I start a project using vite I always get:
`The requested module '/src/store/index.js?t=1659728071243' does not provide an export named 'store'`
 the only way I can solve this is by doing this in store/store.js:
```
export const store = configureStore({
  reducer: {},
})
```

**Comment by markerikson** [comment]
Ah. That's a difference between "named" and "default" imports/exports.

In this case, some other file is doing `import { store } from "./app/store"`.  Note the curly braces making it a _named_ import - if there were no curly braces, it would be a _default_ import.

How are you creating the application in the first place?  One of our CRA templates? A Vite template?  Something else?

**Comment by je34429** [comment]
a vite template for react projects, but I'm doing the import that way:
`import {store} from './store'`

**Comment by je34429** [comment]
the problem is that in the docs first step there is no variable containing the store but in the next step the store gets imported as it has a name:

first step:
```
import { configureStore } from '@reduxjs/toolkit'

export default configureStore({ //no name or variable holding the store
  reducer: {},
})
```

**Comment by markerikson** [comment]
Okay, so this is really a combination of:

- The template you're using is set up a certain way
- The file structure that the "Quick Start" page describes may not exactly match the file structure in that template
- Understanding how JS module syntax works

If you look at the "Quick Start" page, the store file is:

```js
export default configureStore({
  reducer: {},
})
```

which is a default export.  To match that, the example for `index.js` says:

```js
import store from './app/store'
```

which is a default import.  Yes, we give the variable a name, but you can give a default import _any_ name you want.  Like, this is legal:

```js
import fred from './app/store';
// or `import bunny` or `import hiHowAreYou`, etc
```

because that's just how JS default imports work.

In this case I don't think there's anything for us to change here.  We don't control the folder structure in this Vite template, and the "Quick Start" page is meant to show the basic ideas.  We have to assume that users understand how JS module syntax works and can apply any differences to there

**Comment by je34429** [comment]
thank you very much for sharing
