### ISSUE TITLE
ypeError: Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by AbdirahmanJibril** [reduxjs/react-redux#1939]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 
- ReactDOM/React Native: 
- Redux:
- React Redux:

### What is the current behavior?

I am using React/Redux toolkit based on udemy course, the course was based on redux core but i decided to use the toolkit, everything is working perfectly untill i get to a page, in this page I am using useSelector to just show summary of data already in store,  the store has all data but is doesn't load on the browser first time,  if i reload the the browser page it works. what could be happening here 

### What is the expected behavior?

it should load all data already in store for display on browser

### Which browser and OS are affected by this issue?

chrom

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. 

(Also, for future reference: when asking a question, it's _reallly_ important to provide actual source code, error messages, and ideally a working CodeSandbox that shows the problem happening.  Otherwise, no one will have an idea what's going on in your app - we're not psychic :)  )

Thanks!
