### ISSUE TITLE
type for dispatch for old react redux?

### ISSUE THREAD

**Issue by kien-pham** [reduxjs/react-redux#1946]
Hello,

I still using old version of redux (`"react-redux": "^7.2.3", "redux-thunk": "^2.3.0"`) for my web app. I have rootReducer like this, I having issue to create Dispatch type, I have checked the docs but they are just for new redux version.

import { combineReducers } from "redux";

```
// global store
export const rootReducer = combineReducers({
  helper: HelperReducer,
  user: UserReducer,
  playlist: PlaylistReducer,
  author: AuthorReducer,
  category: CategoryReducer,
  hashtag: HashtagReducer,
  video: VideoReducer,
  music: MusicReducer,
  photo: PhotoAlbumReducer,
  comment: CommentReducer
});

export type rootState = ReturnType<typeof rootReducer>;
export type AppDispatch = typeof ??? // <- how to type it?
```

On code, I have error `Argument of type '(dispatch: any) => void' is not assignable to parameter of type 'AnyAction'.ts`

```
import { Dispatch } from 'redux'

const mapDispatchToProps = (dispatch: Dispatch) => {
    return {
        handleLikeOrUnlikeVideo: (action: string, video_id: string, user_id: string, token: string) => { // <- error from this line
            dispatch(_userLikeUnlikeVideo(action, video_id, user_id, token))
        },
        dispatch
    }
}
```

**Comment by markerikson** [comment]
This was originally filed in the Redux Toolkit repo, but I've moved it to the React-Redux repo because it really doesn't have anything to do with RTK.

Several thoughts here:

- We _strongly_ encourage the use of function components + the `useSelector/useDispatch` hooks API instead of `connect` if at all possible
- Similarly, you _should_ be using Redux Toolkit. At a minimum, install `@reduxjs/toolkit` and swap the store setup to use RTK's `configureStore`, and then do the suggested `type AppDispatch = typeof store.dispatch`.  You can leave the rest of the code in place for now, and migrate it to RTK over time.
- Assuming that `handleLikeOrUnlikeVideo` is a thunk based on the error message, the problem is that the core Redux `Dispatch` type doesn't know anything about thunks, so TS is rightfully saying "you can't do that".
- _If_ you're going to use `connect`, [use the "object" form instead of the "function" form](https://react-redux.js.org/using-react-redux/connect-mapdispatch#defining-mapdispatchtoprops-as-an-object), in which case it's just `const mapDispatch = {handleLikeOrUnlikeVideo}` and you don't have to worry about defining a type for `dispatch` here

You can _try_ doing `type AppDispatch = typeof store.dispatch` if you're not using RTK, but it may not pick up the thunk types correctly.
