### ISSUE TITLE
where development or production mode should be specified?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [reduxjs/react-redux#2111]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

Not applicable - documentation

### What is the current behavior?

In The documentation page https://react-redux.js.org/api/hooks#development-mode-checks
It is not clear where development or production mode should be specified , hyperlink to appropriate documentation will be appreciated.

btw, it seems that  search on the page doesn’t work. When I clicked search on the right top corner and typed development, I’ve got “No results for "development"

### What is the expected behavior?

link to appropriate documentation is expected

### Which browser and OS are affected by this issue?

iPad safari 

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
This is standard in all build tools: `process.env.NODE_ENV === "production"` (or `"development"`), typically as managed by a build tool setting for dev or prod.

**Comment by michael-freidgeim-webjet** [comment]
@markerikson  
1. Could  you please add a link to this explanation to the documentation page(s)?
2. Do you experience the same broken search or it doesn’t work only for me?

**Comment by michael-freidgeim-webjet** [comment]
@markerikson another place where link explaining dev/prod mode should be added
https://redux-toolkit.js.org/api/getDefaultMiddleware#development

**Comment by markerikson** [comment]
@michael-freidgeim-webjet I'll be honest, it's not the job of the Redux docs to explain _every_ concept in web development.  There are other articles out there that explain what specific behaviors and settings are part of "dev mode" and "prod mode" in each build tool.

It's the same way that it's not the job of the Redux docs to explain JS syntax, HTML, or React.  We have to assume that our readers know certain concepts already.

**Comment by michael-freidgeim-webjet** [comment]
It is a job of every documentation , when using some concept to give a reference where the concept is described/documented.
It is exactly what I am suggesting- give a link/reference to "other articles out there that explain what specific behaviors and settings are part of "dev mode" and "prod mode"

It is especially important when search on documentation site is broken

Regards,
Michael Freidgeim
________________________________

**Comment by phryneas** [comment]
"dev mode" is not a "Redux" concept, it's a feature of your general application setup - most of the time the framework you are using.

E.g. Next.js, CRA, Vite and many others will provide you with a `dev` script that you trigger by typing `npm run dev` into your console. 
If you skipped this step in the documentation of your framework (and it is most likely already part of the "getting started" section of your framework), you are simply far too late, looking for it in the Redux documentation. It's a concept used by almost every library, and all of them depend on your framework configuration instead of individually documenting this (except if they deviate from ecosystem defaults).

We also cannot link you to any resource about it, since we'd have to link to every possible framework you are using, and each of those probably has different documentation.

Once you start setting up Redux, you are aleady so deep in the game that you should know what "dev mode" is, or at least have a slight idea, based on the fact that you are literally starting your app in "dev mode" 99% of the time you are developing software.

**Comment by timdorr** [comment]
> It is especially important when search on documentation site is broken

Just to address this, I'm showing the search as working on my end: 

<img width="439" alt="image" src="https://github.com/reduxjs/react-redux/assets/17882/addf1e8a-5e6f-4425-b2db-16493dcd5203">

My best guess is a browser extension or something on your network is blocking access to Algolia and preventing it from showing up.
