### ISSUE TITLE
Provider properties for dev checks to be passed explicitly to new devModeChecks property

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [reduxjs/react-redux#2116]
### What is the new or updated feature that you are suggesting?

In page https://react-redux.js.org/api/hooks#development-mode-checks
There are examples of Provider properties settings
Provider store={store} stabilityCheck="always"
Provider store={store} identityFunctionCheck="always"

It is confusing, as it looks like the settings have preference and will be applied to production builds as well.
It will be more clear if the properties will be passed to Provider the same way as for individual selectors by introducing new devModeChecks property

E.g. Provider store={store} devModeChecks:{stabilityCheck:’always’,identityFunctionCheck:’always’}

### Why should this feature be included?

Current names of properties cause confusion, would the setting applied in production or not

### What docs changes are needed to explain this?

 https://react-redux.js.org/api/hooks#development-mode-checks

**Comment by timdorr** [comment]
We don't run those checks in production mode because they will produce errors the user won't see nor will mean anything to them. 

I'm not sure I agree that wrapping these settings in another level of objects makes things more clear. It seems like needless indirection. It doesn't really affect anything, as you will always see these things during dev or test modes and will have the tools to address any issues there. Whereas in production those tools are not usually available.

**Comment by michael-freidgeim-webjet** [comment]
@timdorr  “ We don't run those checks in production mode”
The problem is that the current names usage gives impression for the opposite- that they used in any mode.
When someone sees
`Provider  store={store} stabilityCheck="always"`
they will ask - how to specify, that the flag is applied only in dev mode.

If you don’t want to create a new object, consider to give properties more descriptive names, e.g. devModeStabilityCheck and devModeIdentityFunctionCheck

**Comment by phryneas** [comment]
You will only ever notice that these options exist when you get the according error messages, which will hopefully trigger that you read up on those error messages. 99% of the time after that you won't need those options, but will instead fix your code.

Only in very rare cases you will ever need to set those options. In those cases you will have recognized a need for those options, and looked them up in the documentation - which tells you that they are dev-only checks.

In this case, it seems you only looked at the examples without reading the text above them - the first words are literally "in developement".
![grafik](https://github.com/reduxjs/react-redux/assets/4282439/8c9f9d9c-4eb0-46c3-9de0-7fec418da4cc)

What *might* be a good idea would be that we add docblocks to these options, explaining a little more about them - but generally, these should never be discovered any other way than "I saw the error message and then I read the docs".

Changing their name won't help, since the name still wouldn't explain what they exactly do - in the end we would end up with `devModeCheckThatWillCheckIfYourSelectorReturnsAStableResultForMoreInformationPleaseReadTheDocumentation="once"`.

We can only document so much :/

**Comment by EskiMojo14** [comment]
It's also worth noting that any change to naming or format at this point would be a breaking change, meaning it couldn't be done until the next major release.

**Comment by aryaemami59** [comment]
If you hover over them, the description actually states that they run in development mode.

**Comment by michael-freidgeim-webjet** [comment]
@phryneas “You will only ever notice that these options exist”
People notice when they see the code `Provider  store={store} stabilityCheck="always"` (that likely was set by some other developer”
Self-explaining name is preferred to ambiguous name, that require documentation to understand the functionality.
@EskiMojo14 , yes, it is proposed to consider for the next major release.
@aryaemami59 not every tool/ide supports hover over.

**Comment by phryneas** [comment]
@michael-freidgeim-webjet it's as self-explanatory as `<div>`, `Provider`, `children`, or `store`:
Everything needs to be looked up or learned once. 

The alternative would really be a name that's probably as long as the full documentation - what seems intuitive for you will seem unintuitive for someone else, so we'd end up patching more and more words onto it with every complaint up to the point where it becomes unwieldable.

The current name is fine and we are not going to change it for people who refuse to use a modern IDE or read the documentation. 
If you suspect that someone in your team might see it and not know what it means, you are free to add a comment to your code.

```js
<Provider  store={store} /*devModeOnly*/stabilityCheck="always">{children}</Provider>
```
