### ISSUE TITLE
Single global store and two Provider occurs an error for microfrontend app

### ISSUE THREAD

**Issue by bertanyaman** [reduxjs/react-redux#2132]
### What version of React, ReactDOM/React Native, Redux, and React Redux are you using?

- React: 18.2.0
- ReactDOM: 18.2.0
- Redux: 4.1.2
- React Redux: 8.1.1

### What is the current behavior?

I am getting following warning on application start. But app works fine. Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported. at Provider.

I have an example repo:
https://github.com/bertanyaman/microfrontend-redux

### What is the expected behavior?

I expect to not getting this warning

### Did this work in previous versions of React Redux?

- [ ] Yes

**Comment by markerikson** [comment]
That means you have multiple entirely separate copies of React using the same React context provider instance (in this case, our own `ReactReduxContext`).

This is a React warning, and not specific to React-Redux.

You'll need to either rework your app so that only _one_ copy of React is getting loaded and shared, or use our docs to create an entirely separate custom `ReactReduxContext` instance and rewrite one or more of the MFE instances to use that custom context (which frankly will be painful to do).
