### ISSUE TITLE
Is there any plan to resolve the CVE-2023-45133 vulnerability that depends on the software Babel?

### ISSUE THREAD

**Issue by eaglejuang** [reduxjs/react-redux#2174]
### What is the new or updated feature that you are suggesting?

Currently, we use react-redux 8.1.3. However, the Babel in react-redux 8.1.3 has the CVE-2023-45133  vulnerability. Is there a version released to upgrade Babel?

CVE-2023-45133 Detail:
Babel is a compiler for writingJavaScript. In `@babel/traverse` prior to versions 7.23.2 and 8.0.0-alpha.4 and all versions of `babel-traverse`, using Babel to compile code that was specifically crafted by an attacker can lead to arbitrary code execution during compilation, when using plugins that rely on the `path.evaluate()`or `path.evaluateTruthy()` internal Babel methods. Known affected plugins are `@babel/plugin-transform-runtime`; `@babel/preset-env` when using its `useBuiltIns` option; and any "polyfill provider" plugin that depends on `@babel/helper-define-polyfill-provider`, such as `babel-plugin-polyfill-corejs3`, `babel-plugin-polyfill-corejs2`, `babel-plugin-polyfill-es-shims`, `babel-plugin-polyfill-regenerator`. No other plugins under the `@babel/` namespace are impacted, but third-party plugins might be. Users that only compile trusted code are not impacted. The vulnerability has been fixed in `@babel/traverse@7.23.2` and `@babel/traverse@8.0.0-alpha.4`. Those who cannot upgrade `@babel/traverse` and are using one of the affected packages mentioned above should upgrade them to their latest version to avoid triggering the vulnerable code path in affected `@babel/traverse` versions: `@babel/plugin-transform-runtime` v7.23.2, `@babel/preset-env` v7.23.2, `@babel/helper-define-polyfill-provider` v0.4.3, `babel-plugin-polyfill-corejs2` v0.4.6, `babel-plugin-polyfill-corejs3` v0.8.5, `babel-plugin-polyfill-es-shims` v0.10.0, `babel-plugin-polyfill-regenerator` v0.5.3.

### Why should this feature be included?

NA

### What docs changes are needed to explain this?

NA

**Comment by phryneas** [comment]
Have you read the CVE description that you pasted here?

That CVE would allow us, the developers of the library, to write specific code on purpose that would attack our own machines while we compile the library.

Babel is a devDependency. It only runs on our library author machines and never on user machines. It won't even be installed when you install `react-redux`.

So from that, maybe we update babel one day, but this CVE is definitely not a reason to update anything, because we do not deal with arbitrary code from unknown sources. 
A vulnerability always needs to be triggered, and there is no way to trigger that vulnerability.

Please read https://overreacted.io/npm-audit-broken-by-design/
