### ISSUE TITLE
Ability to obtain store in a component

### ISSUE THREAD

**Issue by sodik82** [reduxjs/react-redux#948]
Hi there,

this is most likely a question or enhancement proposal. I know that I could get store by using old context API - but this looks not to be part of official [API](https://github.com/reactjs/react-redux/blob/master/docs/api.md). It looks to me like the internal implementation that can change (e.g. with new React Context implementation). Is there a official way to retrieve the store?

My motivation:
I am using redux-saga and I like the way how they "enhanced" store in their [example in official API](https://redux-saga.js.org/docs/api/)

```
export default function configureStore(initialState) {
  // Note: passing middleware as the last argument to createStore requires redux@>=3.1.0
  const sagaMiddleware = createSagaMiddleware()
  return {
    ...createStore(reducer, initialState, applyMiddleware(/* other middleware, */sagaMiddleware)),
    runSaga: sagaMiddleware.run
  }
}
```

I would like to execute `runSaga` in my components and therefore need get the `store`. And as store is already provided by `Provider` it would be convenient to able to retrieve it somewhere down the road in official way. 

I know that this is not direct responsibility of `react-redux` but I believe other users could benefit from (or misuse) such feature as well :)

**Comment by markerikson** [comment]
Yeah, accessing the store directly is definitely _not_ part of the public React-Redux API.  Now, because `<Provider>` currently puts the store into the old-style context, I've certainly seen plenty of third-party libraries that access `context.store` and do stuff with it (separate subscriptions, passing down a modified version of the store to descendants, etc).  

When we switch to using the new context API provided by React 16.3, all that unofficial usage will break, because `context.store` will no longer exist.  In addition, the current prototype doesn't even pass down the store to connected components, just the current store state and `dispatch`.  I'm still trying to figure out the best way to support this kind of use case, especially for the kind of situation that you're describing - React components that dynamically add slice reducers or kick off sagas.

That said, there's certainly nothing stopping you from having your own context-based method of passing down the store to your own components.

**Comment by sodik82** [comment]
sure, there are definitely ways around it.

I basically agree that standard use-case does not involve directly playing with `store`, so "easiest" solution might be to provide `injectStore` HOC (or `Consumer` as `Provider` counterpart) for such use-cases.

Thanks for considerations.

**Comment by timdorr** [comment]
For now, you can use the legacy Context API to get access to it.

In the future, when we use the new Context API, we'll provide that context's Consumer as an export, so you can get to it that way.
